"""把 pre-commit / commit-msg 钩子安装到 .git/hooks/（Windows / Unix 通用）。

用法：python scripts/install_hooks.py
"""

from __future__ import annotations

import sys
from pathlib import Path

WRAPPER = """#!/bin/sh
# generated by scripts/install_hooks.py
if command -v python >/dev/null 2>&1; then PY=python
elif command -v python3 >/dev/null 2>&1; then PY=python3
else echo "hook: python not found" >&2; exit 1; fi
exec "$PY" scripts/{script} {extra}
"""


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    git_dir = root / ".git"
    if not git_dir.is_dir():
        print("未找到 .git，请先在项目根执行 git init")
        return 1
    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    (hooks_dir / "pre-commit").write_text(
        WRAPPER.format(script="gate_check.py", extra=""), encoding="utf-8"
    )
    (hooks_dir / "commit-msg").write_text(
        WRAPPER.format(script="commit_msg_check.py", extra='"$1"'), encoding="utf-8"
    )
    print("已安装 pre-commit / commit-msg 钩子")
    return 0


if __name__ == "__main__":
    sys.exit(main())
